workers = 4 # 同时下载文件数
retry = 3   # 下载失败重试次数

[telegram]
token = ""                                    # Bot Token
admins = [7568561381]                             # 你的 user_id
app_id = 20607064                               # Telegram API ID
app_hash = "8117966125:AAG8AsaKB4Gd1kqkOJ9-VgSlftsL_z827M0" # Telegram API Hash

[telegram.proxy]
enable = false
url = "socks5://127.0.0.1:7890" # 代理地址

[log]
level = "DEBUG" # 日志等级

[temp]
base_path = "cache/" # 下载文件临时目录, 请不要在此目录下存放任何其他文件
cache_ttl = 30       # 临时文件保存时间, 单位: 秒

[db]
path = "data/data.db" # 数据库文件路径

[storage]
[storage.alist] # Alist
enable = true
base_path = "/telegram"   # 保存路径
username = "admin"        # 用户名
password = "password"     # 密码
url = "https://alist.com" # Alist 地址
token_exp = 86400         # token 过期时间, 单位: 秒

[storage.local] # 本地磁盘
enable = true
base_path = "downloads/" # 保存路径

[storage.webdav] # WebDav
enable = true
base_path = "/telegram"
username = "admin"
password = "password"
url = "https://alist.com/dav"
